### ISSUE TITLE
installing Trait "Sokeio\Admin\Concerns\WithFormData" not found

### ISSUE THREAD

**Issue by mub009** [sokeio/website-builder#8]
- Installing spatie/flare-client-php (1.4.3): Extracting archive
  - Installing spatie/ignition (1.12.0): Extracting archive
  - Installing spatie/laravel-ignition (2.3.3): Extracting archive
66 package suggestions were added by new dependencies, use `composer suggest` to see details.
Generating optimized autoload files
> @php artisan package:discover --ansi

In WithPageBuilder.php line 8:

  Trait "Sokeio\Admin\Concerns\WithFormData" not found

PHP Fatal error:  Trait "Sokeio\Admin\Concerns\WithFormData" not found in C:\xamppnew\htdocs\project\laravel-grapesjs-builder-community-main\vendor\sokeio\grapesjs-builder\src\WithPageBuilder.php on line 8

PHP Fatal error:  Trait "Sokeio\Admin\Concerns\WithFormData" not found in C:\xamppnew\htdocs\project\laravel-grapesjs-builder-community-main\vendor\sokeio\grapesjs-builder\src\WithPageBuilder.php on line 8
In WithPageBuilder.php line 8:

  Trait "Sokeio\Admin\Concerns\WithFormData" not found

**Comment by devhau** [comment]
@mub009 I Fixed
